### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by wildeyes** [dcrousso/GIFBar#1]
```
>npm i
...
>npm start

App threw an error during load
TypeError: Cannot read property 'hide' of undefined
    at Object.<anonymous> (C:\Users\user\Documents\GIFBar\index.js:6:18)
    at Object.<anonymous> (C:\Users\user\Documents\GIFBar\index.js:172:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (C:\Users\user\Documents\GIFBar\node_modules\electron\dist\resources\default_app.asar\main.js:283:12)
    at Object.<anonymous> (C:\Users\user\Documents\GIFBar\node_modules\electron\dist\resources\default_app.asar\main.js:325:5)
    at Object.<anonymous> (C:\Users\user\Documents\GIFBar\node_modules\electron\dist\resources\default_app.asar\main.js:361:3)
```

**Comment by dcrousso** [comment]
Have you updated (`npm update`) recently?

**Comment by QuadDepo** [comment]
any update on this issue?
